# Example values for secure production deployment
# DO NOT commit this file with real certificates!

# Copy this file and customize for your environment:
# cp values-secure-example.yaml values-production.yaml
# Edit values-production.yaml with your real certificates
# Add values-production.yaml to .gitignore

global:
  namespace: thingsboard-prod

# ThingsBoard configuration
thingsboard:
  node:
    replicas: 2
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "8" 
        memory: 24Gi
  
  transports:
    coap:
      replicas: 10
      dtlsEnabled: true
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/cert-id"

# Infrastructure scaling for production
cassandra:
  resources:
    limits:
      memory: 64Gi
    requests:
      memory: 48Gi
  storage:
    size: 1Ti

kafka:
  replicas: 3
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi
  storage:
    size: 200Gi

redis:
  auth:
    enabled: true
    password: "CHANGE_THIS_STRONG_PASSWORD"
  master:
    resources:
      limits:
        cpu: 2000m
        memory: 8Gi

zookeeper:
  replicas: 3

# Security Configuration - REPLACE WITH YOUR CERTIFICATES
security:
  certificates:
    enabled: true
    dtls:
      # OPTION 1: Set via Helm command line (recommended)
      # helm install ... --set-file security.certificates.dtls.serverCert=./certs/server.pem
      #                  --set-file security.certificates.dtls.serverKey=./certs/server.key
      
      # OPTION 2: Use external secret management (recommended for production)
      # Configure external-secrets-operator or similar to inject certificates
      
      # OPTION 3: Paste certificates here (NOT recommended for version control)
      serverCert: |
        # -----BEGIN CERTIFICATE-----
        # Your actual certificate content here
        # -----END CERTIFICATE-----
        
      serverKey: |
        # -----BEGIN EC PRIVATE KEY-----  
        # Your actual private key content here
        # -----END EC PRIVATE KEY-----

# Autoscaling for high availability
autoscaling:
  enabled: true
  coap:
    minReplicas: 10
    maxReplicas: 50
    targetCPUUtilizationPercentage: 70
  http:
    minReplicas: 5
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70