# Global configuration
global:
  namespace: thingsboard-qa
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# ThingsBoard configuration
thingsboard:
  image:
    registry: thingsboard/tb-pe
    tag: "4.0.1"
    pullPolicy: IfNotPresent
  
  # Core service configuration
  node:
    enabled: true
    replicas: 1
    resources:
      limits:
        memory: 32Gi
      requests:
        memory: 30Gi
    
    # DTLS Configuration
    dtls:
      enabled: true
      certificatesSecret: coap-pem-configmap
      
  # Transport services
  transports:
    coap:
      enabled: true
      replicas: 4
      port: 5684
      dtlsEnabled: true
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      resources:
        limits:
          cpu: 410m
          memory: 8Gi
        requests:
          cpu: 410m
          memory: 8Gi
    
    http:
      enabled: true
      replicas: 1
      port: 8080
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    
    mqtt:
      enabled: true
      replicas: 1
      port: 1883

# Database configuration
cassandra:
  enabled: true
  cluster:
    name: cassandra
    datacenter: dc1
    rack: rack1
  resources:
    limits:
      memory: 32Gi
    requests:
      memory: 30Gi

# Message queue configuration
kafka:
  enabled: true
  replicas: 3
  resources:
    limits: {}
    requests: {}

# Cache configuration
redis:
  enabled: true
  master:
    resources:
      limits: {}
      requests: {}

# Zookeeper configuration
zookeeper:
  enabled: true
  replicas: 3
  resources:
    limits: {}
    requests: {}

# Web UI configuration
webui:
  enabled: true
  replicas: 1
  service:
    type: LoadBalancer
    port: 8080

# JS Executor configuration
jsExecutor:
  enabled: true
  replicas: 1
  resources:
    limits: {}
    requests: {}

# Horizontal Pod Autoscaling
autoscaling:
  enabled: true
  coap:
    minReplicas: 4
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  http:
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  mqtt:
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

# Monitoring and logging
monitoring:
  enabled: true
  namespace: monitoring

# Security
security:
  certificates:
    enabled: true
  secrets:
    enabled: true