apiVersion: apps/v1
kind: StatefulSet
metadata:
	name: zookeeper
spec:
	selector:
		matchLabels:
			app: zookeeper
	serviceName: zookeeper
	replicas: 1
	template:
		metadata:
			labels:
				app: zookeeper
		spec:
			imagePullSecrets:
				- name: harbor-zookeeper-pull-secret
			containers:
				- name: zookeeper
					image: harbor.qa.stagezero.co.za/zookeeper/zookeeper:3.9.4-jre-17
					ports:
						- containerPort: 2181
