apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  replicas: {{ .Values.zookeeper.replicas }}
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      imagePullSecrets:
        - name: harbor-zookeeper-pull-secret
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image.registry }}:{{ .Values.zookeeper.image.tag }}
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOOKEEPER_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "10"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "5"
            - name: ZOOKEEPER_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
              value: "3"
            - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
              value: "1"
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
            - name: zookeeper-logs
              mountPath: /var/lib/zookeeper/log
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.zookeeper.storage.storageClass }}
        storageClassName: {{ .Values.zookeeper.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.zookeeper.storage.size }}
    - metadata:
        name: zookeeper-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.zookeeper.storage.storageClass }}
        storageClassName: {{ .Values.zookeeper.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: 10Gi