{{- if .Values.thingsboard.transports.coap.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thingsboard-pe.fullname" . }}-coap-transport
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app.kubernetes.io/component: coap-transport
spec:
  replicas: {{ .Values.thingsboard.transports.coap.replicas }}
  serviceName: {{ include "thingsboard-pe.fullname" . }}-coap-transport
  selector:
    matchLabels:
      {{- include "thingsboard-pe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: coap-transport
  template:
    metadata:
      labels:
        {{- include "thingsboard-pe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: coap-transport
    spec:
      containers:
      - name: thingsboard-coap
        image: "{{ .Values.thingsboard.transports.coap.image.registry }}:{{ .Values.thingsboard.transports.coap.image.tag }}"
        imagePullPolicy: {{ .Values.thingsboard.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.thingsboard.transports.coap.port }}
          name: coap-dtls
          protocol: UDP
        env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_QUEUE_TYPE
          value: kafka
        - name: METRICS_ENABLED
          value: "true"
        - name: WEB_APPLICATION_ENABLE
          value: "true"
        - name: HTTP_BIND_PORT
          value: "8082"
        - name: TB_KAFKA_SERVERS
          value: {{ .Values.thingsboard.transports.coap.env.TB_KAFKA_SERVERS | quote }}
        - name: COAP_TIMEOUT
          value: {{ .Values.thingsboard.transports.coap.env.COAP_TIMEOUT | quote }}
        - name: TB_QUEUE_REQUEST_TIMEOUT
          value: {{ .Values.thingsboard.transports.coap.env.TB_QUEUE_REQUEST_TIMEOUT | quote }}
        {{- if .Values.thingsboard.transports.coap.dtlsEnabled }}
        - name: COAP_DTLS_ENABLED
          value: "true"
        - name: COAP_DTLS_CREDENTIALS_TYPE
          value: PEM
        - name: COAP_DTLS_PEM_CERT
          value: /https-config/server.pem
        - name: COAP_DTLS_PEM_KEY
          value: /https-config/server_key.pem
        - name: COAP_DTLS_BIND_PORT
          value: {{ .Values.thingsboard.transports.coap.port | quote }}
        - name: COAP_DTLS_BIND_ADDRESS
          value: "0.0.0.0"
        {{- end }}
        - name: COAP_TRANSPORT_HOST
          value: {{ printf "%s-coap.%s.svc.cluster.local" (include "thingsboard-pe.fullname" .) (include "thingsboard-pe.namespace" .) }}
        resources:
          {{- toYaml .Values.thingsboard.transports.coap.resources | nindent 10 }}
        volumeMounts:
        - name: thingsboard-coap-transport-config
          mountPath: /config
        {{- if .Values.thingsboard.transports.coap.dtlsEnabled }}
        - name: coap-pem-configmap
          mountPath: /https-config
        {{- end }}
        - name: coap-gc-logs
          mountPath: /var/log/tb
      volumes:
      - name: thingsboard-coap-transport-config
        configMap:
          name: thingsboard-coap-transport-config
          items:
          - key: conf
            path: tb-coap-transport.conf
          - key: logback
            path: logback.xml
      {{- if .Values.thingsboard.transports.coap.dtlsEnabled }}
      - name: coap-pem-configmap
        configMap:
          name: {{ .Values.thingsboard.node.dtls.certificatesConfigMap }}
          defaultMode: 444
          items:
          - key: server.pem
            path: server.pem
          - key: server_key.pem
            path: server_key.pem
      {{- end }}
      - name: coap-gc-logs
        emptyDir: {}
  updateStrategy:
    type: RollingUpdate
{{- end }}
