apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["a30d8ce0abd1344fb9cf0e9a99ce1c33-5f689966a75b6be1.elb.af-south-1.amazonaws.com"],"port":5684,"protocol":"UDP","serviceName":"thingsboard-qa:thingsboard-coap","allNodes":false}]'
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  creationTimestamp: "2025-09-19T05:38:44Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thingsboard
    app.kubernetes.io/version: 3.5.1
    helm.sh/chart: thingsboard-0.1.4-rc.51
    k8slens-edit-resource-version: v1
    k10.kasten.io/actionType: snapshot
    k10.kasten.io/appName: thingsboard-qa
    k10.kasten.io/policyName: thingsboard-qa-backup
  name: thingsboard-coap-transport
  namespace: thingsboard-qa
  resourceVersion: "211784358"
  uid: 785c4f12-48c1-4c2c-8e8e-e15ce0f16cc4
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: thingsboard-coap
      app.kubernetes.io/name: thingsboard-coap
  serviceName: tb-coap-transport
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-09-19T07:43:33+02:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: thingsboard-coap
        app.kubernetes.io/name: thingsboard-coap
    spec:
      containers:
      - env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: TB_QUEUE_TYPE
          value: kafka
        - name: METRICS_ENABLED
          value: "true"
        - name: METRICS_ENDPOINTS_EXPOSE
          value: prometheus
        - name: WEB_APPLICATION_ENABLE
          value: "true"
        - name: WEB_APPLICATION_TYPE
          value: servlet
        - name: HTTP_BIND_PORT
          value: "8082"
        - name: COAP_TIMEOUT
          value: "60000"
        - name: TB_KAFKA_SERVERS
          value: thingsboard-kafka:9092
        - name: TB_QUEUE_KAFKA_REPLICATION_FACTOR
          value: "1"
        - name: COAP_DTLS_ENABLED
          value: "true"
        - name: COAP_DTLS_CREDENTIALS_TYPE
          value: PEM
        - name: COAP_DTLS_PEM_CERT
          value: /https-config/server.pem
        - name: COAP_DTLS_PEM_KEY
          value: /https-config/server_key.pem
        - name: COAP_TRANSPORT_HOST
          value: thingsboard-coap.thingsboard-qa.svc.cluster.local
        - name: COAP_DTLS_BIND_PORT
          value: "5684"
        - name: COAP_DTLS_BIND_ADDRESS
          value: 0.0.0.0
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1g
        - name: TB_QUEUE_REQUEST_TIMEOUT
          value: "120000"
        - name: TB_KAFKA_REQUEST_TIMEOUT_MS
          value: "120000"
        - name: TB_KAFKA_SESSION_TIMEOUT_MS
          value: "30000"
        image: docker.io/thingsboard/tb-pe-coap-transport:4.0.1PE
        imagePullPolicy: Always
        name: thingsboard
        ports:
        - containerPort: 5684
          name: coap-dtls
          protocol: UDP
        resources:
          limits:
            cpu: 410m
            memory: 8Gi
          requests:
            cpu: 410m
            memory: 8Gi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: thingsboard-coap-transport-config
        - mountPath: /https-config
          name: coap-pem-configmap
        - mountPath: /var/log/tb
          name: coap-gc-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: thingsboard-node-sa
      serviceAccountName: thingsboard-node-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: conf
            path: tb-coap-transport.conf
          - key: logback
            path: logback.xml
          name: thingsboard-coap-transport-config
        name: thingsboard-coap-transport-config
      - configMap:
          defaultMode: 444
          items:
          - key: server.pem
            path: server.pem
          - key: server_key.pem
            path: server_key.pem
          name: coap-pem-configmap
        name: coap-pem-configmap
      - emptyDir: {}
        name: thingsboard-node-logs
      - emptyDir: {}
        name: coap-gc-logs
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 4
  collisionCount: 0
  currentReplicas: 4
  currentRevision: thingsboard-coap-transport-849498c54d
  observedGeneration: 3
  readyReplicas: 4
  replicas: 4
  updateRevision: thingsboard-coap-transport-849498c54d
  updatedReplicas: 4
