{{- if .Values.thingsboard.node.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thingsboard-pe.fullname" . }}-node
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
spec:
  replicas: {{ .Values.thingsboard.node.replicas }}
  serviceName: {{ include "thingsboard-pe.fullname" . }}-node
  selector:
    matchLabels:
      {{- include "thingsboard-pe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node
  template:
    metadata:
      labels:
        {{- include "thingsboard-pe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: wait-for-cassandra
        image: cassandra:5.0.6
        command:
        - sh
        - -c
        - |
          until cqlsh cassandra.{{ include "thingsboard-pe.namespace" . }}.svc.cluster.local -u cassandra -p cassandra -e "DESCRIBE KEYSPACES;" | grep thingsboard; do
            echo "Waiting for Cassandra to be ready and have thingsboard keyspace..."
            sleep 10
          done
          echo "Cassandra is ready with thingsboard keyspace!"
      containers:
      - name: thingsboard-node
        image: "{{ .Values.thingsboard.image.registry }}:{{ .Values.thingsboard.image.tag }}"
        imagePullPolicy: {{ .Values.thingsboard.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9090
          name: rpc
          protocol: TCP
        env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_LICENSE_SECRET
          valueFrom:
            secretKeyRef:
              name: thingsboard-license
              key: license-key
        - name: TB_LICENSE_SERVER_URL
          value: "https://license.thingsboard.io"
        - name: TB_LICENSE_CHECK_INTERVAL_MS
          value: "60000"
        - name: TB_LICENSE_RETRY_INTERVAL_MS
          value: "10000"
        - name: TB_LICENSE_VALIDATION_ENABLED
          value: "true"
        - name: TB_LICENSE_VALIDATION_RETRY_COUNT
          value: "10"
        - name: TB_LICENSE_VALIDATION_RETRY_DELAY_MS
          value: "30000"
        - name: SWAGGER_ENABLED
          value: {{ .Values.thingsboard.node.env.SWAGGER_ENABLED | quote }}
        - name: TB_KAFKA_SERVERS
          value: {{ .Values.thingsboard.node.env.TB_KAFKA_SERVERS | quote }}
        - name: CASSANDRA_URL
          value: cassandra.{{ include "thingsboard-pe.namespace" . }}.svc.cluster.local:9042
        {{- if .Values.thingsboard.node.dtls.enabled }}
        - name: COAP_DTLS_ENABLED
          value: "true"
        - name: COAP_DTLS_CREDENTIALS_TYPE
          value: PEM
        - name: COAP_DTLS_PEM_CERT
          value: /https-config/server.pem
        - name: COAP_DTLS_PEM_KEY
          value: /https-config/server_key.pem
        - name: COAP_DTLS_BIND_PORT
          value: {{ .Values.thingsboard.transports.coap.port | quote }}
        - name: COAP_DTLS_BIND_ADDRESS
          value: "0.0.0.0"
        {{- end }}
        - name: COAP_TRANSPORT_HOST
          value: {{ printf "%s-coap.%s.svc.cluster.local" (include "thingsboard-pe.fullname" .) (include "thingsboard-pe.namespace" .) }}
        envFrom:
        - configMapRef:
            name: thingsboard-node-db-config
        resources:
          {{- toYaml .Values.thingsboard.node.resources | nindent 10 }}
        volumeMounts:
        - name: thingsboard-node-config
          mountPath: /config
        - name: thingsboard-node-logs
          mountPath: /var/log/thingsboard
        - name: gc-logs
          mountPath: /var/log/tb
        - name: thingsboard-node-data
          mountPath: /data
        {{- if .Values.thingsboard.node.dtls.enabled }}
        - name: coap-pem-configmap
          mountPath: /https-config
        {{- end }}
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: thingsboard-node-config
        configMap:
          name: thingsboard-node-config
          items:
          - key: conf
            path: thingsboard.conf
          - key: logback
            path: logback.xml
      - name: thingsboard-node-logs
        emptyDir: {}
      - name: gc-logs
        emptyDir: {}
      - name: thingsboard-node-data
        emptyDir: {}
      {{- if .Values.thingsboard.node.dtls.enabled }}
      - name: coap-pem-configmap
        configMap:
          name: {{ .Values.thingsboard.node.dtls.certificatesConfigMap }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
{{- end }}
