apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: {{ .Values.kafka.replicas }}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      imagePullSecrets:
        - name: harbor-kafka-pull-secret
      containers:
        - name: kafka
          image: {{ .Values.kafka.image.registry }}:{{ .Values.kafka.image.tag }}
          command:
            - /bin/bash
            - -c
            - |
              /etc/kafka/docker/run
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ .Values.zookeeper.serviceName }}.{{ include "thingsboard-pe.namespace" . }}.svc.cluster.local:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(MY_POD_NAME).kafka.{{ include "thingsboard-pe.namespace" . }}.svc.cluster.local:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.kafka.storage.storageClass }}
        storageClassName: {{ .Values.kafka.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.kafka.storage.size }}