apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      imagePullSecrets:
        - name: harbor-cassandra-pull-secret
      containers:
        - name: cassandra
          image: {{ .Values.cassandra.image.registry }}:{{ .Values.cassandra.image.tag }}
          ports:
            - containerPort: 9042
          resources:
            limits:
              memory: {{ .Values.cassandra.resources.limits.memory }}
            requests:
              memory: {{ .Values.cassandra.resources.requests.memory }}