apiVersion: v1
kind: Secret
metadata:
  name: harbor-zookeeper-pull-secret
  namespace: {{ include "thingsboard-pe.namespace" . }}
  annotations:
    argocd.argoproj.io/compare-options: Ignore
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucWEuc3RhZ2V6ZXJvLmNvLnphIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImQ2U2pOTjg0TnU0UVgxZ0VIaktCUWQiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYXV0aCI6IllXUnRhVzQ2WkRaVGFrNU9PRFJPZFRSUldERm5SVWhxUzBKUlpBPT0ifX19