apiVersion: v1
kind: Secret
metadata:
  name: harbor-zookeeper-pull-secret
  namespace: thingsboard-qa
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: IHsiY3JlYXRpb25fdGltZSI6IjIwMjUtMTEtMTdUMDk6MjI6NDkuMDg2WiIsImV4cGlyZXNfYXQiOi0xLCJpZCI6MTIsIm5hbWUiOiJyb2JvdCR6b29rZWVwZXIrem9va2VlcGVyIiwic2VjcmV0IjoiVzRwVWpSem1PdkRrYXl0WTVVSVhiRUlxTUcxZFYzNmoifQ==