apiVersion: v1
kind: Secret
metadata:
  name: harbor-redis-pull-secret
  namespace: thingsboard-qa
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: IHsiY3JlYXRpb25fdGltZSI6IjIwMjUtMTEtMTdUMDk6MjY6NTEuNzI3WiIsImV4cGlyZXNfYXQiOi0xLCJpZCI6MTMsIm5hbWUiOiJyb2JvdCRyZWRpcytyZWRpcyIsInNlY3JldCI6IjQ3a0E1S3JZcExzZjFjR2IycWR5d1NSbmhvY3hwZHRYIn0=