apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.masterServiceName }}
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    app: redis
    component: master
spec:
  ports:
    - name: tcp-redis
      protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redis
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
