apiVersion: apps/v1
kind: Deployment
metadata:
  name: thingsboard-redis-master
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
    component: master
spec:
  replicas: {{ .Values.redis.master.replicas | default 3 }}
  selector:
    matchLabels:
      app: redis
      component: master
  template:
    metadata:
      labels:
        app: redis
        component: master
    spec:
      imagePullSecrets:
        - name: harbor-redis-pull-secret
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          command: ["redis-server"]
          args: ["/etc/redis/redis.conf"]
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
            - name: REDIS_PORT
              value: "6379"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1001
