{{- if .Values.security.certificates.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.thingsboard.node.dtls.certificatesConfigMap }}
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
data:
  server.pem: |
{{ .Values.security.certificates.dtls.serverCert | indent 4 }}
  server_key.pem: |
{{ .Values.security.certificates.dtls.serverKey | indent 4 }}
{{- end }}
