{{- if .Values.thingsboard.node.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thingsboard-pe.fullname" . }}-node
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: rpc
    protocol: TCP
    name: rpc
  selector:
    {{- include "thingsboard-pe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node
{{- end }}
