{{- if .Values.thingsboard.transports.http.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thingsboard-pe.fullname" . }}-http-transport
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-transport
spec:
  serviceName: {{ include "thingsboard-pe.fullname" . }}-http-transport
  replicas: {{ .Values.thingsboard.transports.http.replicas }}
  selector:
    matchLabels:
      {{- include "thingsboard-pe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http-transport
  template:
    metadata:
      labels:
        {{- include "thingsboard-pe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: http-transport
    spec:
      containers:
      - name: http-transport
        image: "{{ .Values.thingsboard.transports.http.image.registry }}:{{ .Values.thingsboard.transports.http.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.thingsboard.transports.http.port }}
          name: http
        env:
        - name: TB_KAFKA_SERVERS
          value: "{{ include "thingsboard-pe.fullname" . }}-kafka:9092"
        - name: HTTP_BIND_ADDRESS
          value: "0.0.0.0"
        - name: HTTP_BIND_PORT
          value: "{{ .Values.thingsboard.transports.http.port }}"
        - name: HTTP_REQUEST_TIMEOUT
          value: "60000"
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.thingsboard.transports.http.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.thingsboard.transports.http.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: http-transport-config
          mountPath: /config
        resources:
          {{- toYaml .Values.thingsboard.transports.http.resources | nindent 10 }}
      volumes:
      - name: http-transport-config
        configMap:
          name: {{ include "thingsboard-pe.fullname" . }}-http-transport-config
          items:
          - key: conf
            path: tb-http-transport.conf
          - key: logback
            path: logback.xml
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thingsboard-pe.fullname" . }}-http-transport
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-transport
  {{- if .Values.thingsboard.transports.http.service.annotations }}
  annotations:
    {{- toYaml .Values.thingsboard.transports.http.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.thingsboard.transports.http.service.type }}
  selector:
    {{- include "thingsboard-pe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http-transport
  ports:
  - port: {{ .Values.thingsboard.transports.http.port }}
    targetPort: {{ .Values.thingsboard.transports.http.port }}
    protocol: TCP
    name: http
{{- end }}